### ISSUE TITLE
'Missing' paper

### ISSUE THREAD

**Issue by everthemore** [physicsml/physicsml.github.io#1]
Learning Disordered Topological Phases by Statistical Recovery of Symmetry
Nobuyuki Yoshioka, Yutaka Akagi, Hosho Katsura
https://arxiv.org/abs/1709.05790

**Comment by emstoudenmire** [comment]
Thanks for letting us know. Just added it in the latest site update.

**Comment by blokhin** [comment]
Hi Miles,

are *issues* the recommended place to propose new papers?

**Comment by emstoudenmire** [comment]
Hi, so actually the preferred way to propose new papers would be by creating a pull request that we can just immediately merge. But if you don’t want to do that, I understand, and it’s fine to just post an issue.

Best regards, Miles
